Ecommerce_GP/Controllers/CartController.cs
using GP.Business.Interfaces;
using GP.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce_GP.Controllers
{
<<<<<<< HEAD
    [Authorize(Roles = "Customer")]
=======
    [Authorize (Roles ="Customer")]
>>>>>>> 88f5b6972038202f1d1b220064a20758c3447c07
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly UserManager<ApplicationUser> _userManager;

        public CartController(ICartService cartService, UserManager<ApplicationUser> userManager)
        {
            _cartService = cartService;
            _userManager = userManager;
        }

<<<<<<< HEAD
        // Show Cart
=======
>>>>>>> 88f5b6972038202f1d1b220064a20758c3447c07
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var cartItems = await _cartService.GetCartItemsAsync(userId);
<<<<<<< HEAD
            var totalAmount = await _cartService.GetTotalAmountAsync(userId); // Get total price for cart
            ViewBag.TotalAmount = totalAmount; // Pass total to the view
            return View(cartItems);
        }

        // Add to Cart
=======
            return View(cartItems);
        }

>>>>>>> 88f5b6972038202f1d1b220064a20758c3447c07
        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId)
        {
            var userId = _userManager.GetUserId(User);
            await _cartService.AddToCartAsync(userId, productId);
            return RedirectToAction("Index");
        }

<<<<<<< HEAD
        // Remove from Cart
=======
>>>>>>> 88f5b6972038202f1d1b220064a20758c3447c07
        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int productId)
        {
            var userId = _userManager.GetUserId(User);
            await _cartService.RemoveFromCartAsync(userId, productId);
            return RedirectToAction("Index");
<<<<<<< HEAD
        }

        // Increase Quantity
        [HttpPost]
        public async Task<IActionResult> IncreaseQuantity(int productId)
        {
            var userId = _userManager.GetUserId(User);
            await _cartService.IncreaseQuantityAsync(userId, productId);
            return RedirectToAction("Index");
        }

        // Decrease Quantity
        [HttpPost]
        public async Task<IActionResult> DecreaseQuantity(int productId)
        {
            var userId = _userManager.GetUserId(User);
            await _cartService.DecreaseQuantityAsync(userId, productId);
            return RedirectToAction("Index");
        }

        // Clear Cart
        [HttpPost]
        public async Task<IActionResult> ClearCart()
        {
            var userId = _userManager.GetUserId(User);
            await _cartService.ClearCartAsync(userId);
            return RedirectToAction("Index");
=======
>>>>>>> 88f5b6972038202f1d1b220064a20758c3447c07
        }
    }
}

Ecommerce_GP/Controllers/ProductController.cs
<<<<<<< HEAD
﻿
using GP.Business.Interfaces;
=======
﻿using GP.Business.Interfaces;
>>>>>>> 88f5b6972038202f1d1b220064a20758c3447c07
using GP.Business.Services;
using GP.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using System.Threading.Tasks;

namespace Ecommerce_GP.Controllers
{
<<<<<<< HEAD

=======
    
>>>>>>> 88f5b6972038202f1d1b220064a20758c3447c07
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetAllProductsAsync();
            return View(products);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Product product, IFormFile file)
        {
            if (file != null && file.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    product.Image = memoryStream.ToArray();
                }
            }

            await _productService.AddProductAsync(product);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int id)
        {
            var product = await _productService.GetProductByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(Product updatedProduct)
        {
            await _productService.UpdateProductAsync(updatedProduct);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            await _productService.DeleteProductAsync(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> WirelessHeadphonesIndex()
        {
            var products = await _productService.GetAllProductsAsync();
            ViewBag.Model = products.Where(p => p.Category == Category.WirelessHeadphones).ToList();
            return View();
        }

        public async Task<IActionResult> TabletProIndex()
        {
            var products = await _productService.GetAllProductsAsync();
            ViewBag.Model = products.Where(p => p.Category == Category.TabletPro).ToList();
            return View();
        }

        public async Task<IActionResult> SmartwatchIndex()
        {
            var products = await _productService.GetAllProductsAsync();
            ViewBag.Model = products.Where(p => p.Category == Category.Smartwatch).ToList();
            return View();
        }

        public async Task<IActionResult> ProfessionalCameraIndex()
        {
            var products = await _productService.GetAllProductsAsync();
            ViewBag.Model = products.Where(p => p.Category == Category.ProfessionalCamera).ToList();
            return View();
        }

        public async Task<IActionResult> GamingLaptopIndex()
        {
            var products = await _productService.GetAllProductsAsync();
            ViewBag.Model = products.Where(p => p.Category == Category.GamingLaptop).ToList();
            return View();
        }

        public async Task<IActionResult> FlagshipSmartphoneIndex()
        {
            var products = await _productService.GetAllProductsAsync();
            ViewBag.Model = products.Where(p => p.Category == Category.FlagshipSmartphone).ToList();
            return View();
        }




    }
}

Ecommerce_GP/Controllers/ReviewController.cs
using GP.Business.Services;
using Microsoft.AspNetCore.Mvc;
using GP.Data.Entities;
using System.Threading.Tasks;


namespace Ecommerce_GP.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ReviewService _reviewService;

        public ReviewController(ReviewService reviewService)
        {
            _reviewService = reviewService;
        }

        public IActionResult Index(int productId)
        {
            if (productId == 0)
            {
                return NotFound();
            }
            List<Review> reviews = _reviewService.GetReviewsByProductId(productId);
            return View(reviews);
        }

        public IActionResult Details(int id)
        {
            var review = _reviewService.GetReviewById(id);
            if (review == null)
                return NotFound();
            return View(review);
        }

        public IActionResult AddReview(int productId)
        {
            var review = new Review { ProductID = productId, CreateDate = DateTime.Now };
            return View(review);
        }

        [HttpPost]
        public IActionResult AddReview(Review review)
        {
            if (ModelState.IsValid)
            {
                bool isAdded = _reviewService.AddReview(review);
                if (isAdded)
                    return RedirectToAction("Details", "Product", new { id = review.ProductID });
            }
            return View(review);
        }





    }
}

Ecommerce_GP/Views/Product/Create.cshtml
@model  GP.Data.Entities.Product

@{
    ViewData["Title"] = "Add Product";
}

<h2>Add New Product</h2>

<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Price" class="control-label"></label>
        <input asp-for="Price" class="form-control" type="number" step="0.01" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="StockQuantity" class="control-label"></label>
        <input asp-for="StockQuantity" class="form-control" type="number" />
        <span asp-validation-for="StockQuantity" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Category" class="control-label"></label>
        <select asp-for="Category" asp-items="Html.GetEnumSelectList<GP.Data.Entities.Category>()" class="form-control">
            <option value="">Select Category</option>
        </select>
        <span asp-validation-for="Category" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Brand" class="control-label"></label>
        <input asp-for="Brand" class="form-control" />
    </div>

    <div class="form-group">
        <label for="ImageFile" class="control-label">Product Image</label>
        <input type="file" name="file" class="form-control" accept="image/*" required />
    </div>

    <div class="form-group mt-3">
        <button type="submit" class="btn btn-success">Save</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Ecommerce_GP/Views/Product/Details.cshtml
@model GP.Data.Entities.Product
@{
    var product = Model;
}


<!-- Background Image Section -->
<div class="bg-container">
    <img src="/img/Details.jpg" alt="Product Banner" class="bg-image">
    <div class="overlay-content">
        <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">Product Details</h1>
        <div class="d-inline-flex mb-lg-5">
            <p class="m-0 text-white"><a class="text-white" href="Index">Home</a></p>
            <p class="m-0 text-white px-2">/</p>
            <p class="m-0 text-white">Product</p>
            <p class="m-0 text-white px-2">/</p>
            <p class="m-0 text-white">Product Details</p>
        </div>
    </div>
</div>

<!-- Product Details Section -->
<div class="product-box">
    <!-- Product Image -->
    <div class="product-image">
        @if (product.Image != null)
        {
            var base64 = Convert.ToBase64String(product.Image);
            var imgSrc = $"data:image/png;base64,{base64}";
            <img src="@imgSrc" alt="@product.Name">
        }
    </div>

    <!-- Product Info -->
    <div class="product-info">
        <h1 class="product-title">@Html.DisplayFor(modelItem => product.Name)</h1>
        <p class="product-category">Category: @Html.DisplayFor(modelItem => product.Category)</p>
        <span class="product-price">@Html.DisplayFor(modelItem => product.Price) EGP</span>

        <!-- Action Buttons -->
        @* <div class="product-actions">
            <button type="submit" class="buy-btn">Add to Cart</button>
            <button class="review-btn">Show Reviews</button> <!-- Reviews Button -->
        </div> *@
        <div class="button-group">
            <a asp-controller="Review" asp-action="Index" asp-route-productId="@product.ProductID"
                class="btn custom-blue-btn">
                Show Reviews
            </a>
            <a href="#" class="btn custom-yellow-btn">Add to Cart</a>
            @* <a asp-controller="Review" asp-action="AddReview" class="btn custom-blue-btn">Add Review</a> *@
        </div>

        <!-- Product Description -->
        <div class="product-description">
            <h3>Description</h3>
            <p><b>@Html.DisplayFor(modelItem => product.Description)</p>
            <p><b>Stock:</b> @Html.DisplayFor(modelItem => product.StockQuantity)</p>
            <p><b>Brand:</b>@Html.DisplayFor(modelItem => product.Brand)</p>
        </div>
    </div>
</div>

Ecommerce_GP/Views/Product/FlagshipSmartphoneIndex.cshtml
@* @model List<E_commerce_platform.Models.Product> *@


<!-- Background Image Section -->
<div class="bg-container">
    <img src="/img/Product.jpg" alt="Review Banner" class="bg-image">
    <div class="overlay-content">
        <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">Products</h1>
        <div class="d-inline-flex mb-lg-5">
            <p class="m-0 text-white"><a class="text-white" href="Index">Home</a></p>
            <p class="m-0 text-white px-2">/</p>
            <p class="m-0 text-white">Products</p>
        </div>
    </div>
</div>

<!-- Product Cards Section -->
<div class="container product-container">
    <h2 class="text-center fw-bold mb-4">You Can Shop New ..</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var product in (IEnumerable<GP.Data.Entities.Product>)ViewBag.Model)
        {
            <div class="col">
                <div class="card h-100 custom-card shadow-lg">
                    <div class="image-container">
                        @if (product.Image != null)
                        {
                            var img = Convert.ToBase64String(product.Image);
                            var path = $"data:image/png;base64,{img}";
                            <img src="@path" alt="@product.Name" class="card-img-top">
                        }
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title">@product.Name.ToString()</h5>
                        <p class="product-price">@product.Price.ToString()$</p>
                        <p class="card-text">Short product description goes here.</p>
                        <div class="button-group">
                            <a asp-action="Details" asp-route-id="@product.ProductID" class="btn custom-blue-btn">Show Details</a>
                            <a href="#" class="btn custom-yellow-btn">Add to Cart</a>
                            @* <a asp-controller="Review" asp-action="AddReview" class="btn custom-blue-btn">Add Review</a> *@
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

Ecommerce_GP/Views/Product/GamingLaptopIndex.cshtml
@* @model List<E_commerce_platform.Models.Product> *@


<!-- Background Image Section -->
<div class="bg-container">
    <img src="/img/Product.jpg" alt="Review Banner" class="bg-image">
    <div class="overlay-content">
        <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">Products</h1>
        <div class="d-inline-flex mb-lg-5">
            <p class="m-0 text-white"><a class="text-white" href="Index">Home</a></p>
            <p class="m-0 text-white px-2">/</p>
            <p class="m-0 text-white">Products</p>
        </div>
    </div>
</div>

<!-- Product Cards Section -->
<div class="container product-container">
    <h2 class="text-center fw-bold mb-4">You Can Shop New ..</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var product in (IEnumerable<GP.Data.Entities.Product>)ViewBag.Model)
        {
            <div class="col">
                <div class="card h-100 custom-card shadow-lg">
                    <div class="image-container">
                        @if (product.Image != null)
                        {
                            var img = Convert.ToBase64String(product.Image);
                            var path = $"data:image/png;base64,{img}";
                            <img src="@path" alt="@product.Name" class="card-img-top">
                        }
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title">@product.Name.ToString()</h5>
                        <p class="product-price">@product.Price.ToString()$</p>
                        <p class="card-text">Short product description goes here.</p>
                        <div class="button-group">
                            <a asp-action="Details" asp-route-id="@product.ProductID" class="btn custom-blue-btn">Show Details</a>
                            <a href="#" class="btn custom-yellow-btn">Add to Cart</a>
                            @* <a asp-controller="Review" asp-action="AddReview" class="btn custom-blue-btn">Add Review</a> *@
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

Ecommerce_GP/Views/Product/GetProduct.cshtml
@* <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="..." class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>
</div> *@

Ecommerce_GP/Views/Product/Index.cshtml
<!-- Background Image Section -->
<div class="bg-container">
    <img src="/img/Product.jpg" alt="Review Banner" class="bg-image">
    <div class="overlay-content">
        <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">Products</h1>
        <div class="d-inline-flex mb-lg-5">
            <p class="m-0 text-white"><a class="text-white" href="Index">Home</a></p>
            <p class="m-0 text-white px-2">/</p>
            <p class="m-0 text-white">Products</p>
        </div>
    </div>
</div>

<!-- Product Cards Section -->
<div class="container product-container">
    <h2 class="text-center fw-bold mb-4">You Can Shop New ..</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var product in Model)
        {
            <div class="col">
                <div class="card h-100 custom-card shadow-lg">
                    <div class="image-container">
                        @if (product.Image != null)
                        {
                            var img = Convert.ToBase64String(product.Image);
                            var path = $"data:image/png;base64,{img}";
                            <img src="@path" alt="@product.Name" class="card-img-top">
                        }
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title">@product.Name.ToString()</h5>
                        <p class="product-price">@product.Price.ToString()$</p>
                        <p class="card-text">Short product description goes here.</p>
                        <div class="button-group">
                            <a asp-action="Details" asp-route-id="@product.ProductID" class="btn custom-blue-btn">Show Details</a>
                            <form class="btn custom-yellow-btn" asp-controller="Cart" asp-action="AddToCart" method="post">
                                <input type="hidden" value="@product.ProductID" name="ProductId" />
                                <button type="submit" style="all:unset;">Add to Cart</button>
                            </form>
                            @* <a asp-controller="Review" asp-action="AddReview" class="btn custom-blue-btn">Add Review</a> *@
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

Ecommerce_GP/Views/Product/ProfessionalCameraIndex.cshtml
@* @model List<E_commerce_platform.Models.Product> *@


<!-- Background Image Section -->
<div class="bg-container">
    <img src="/img/Product.jpg" alt="Review Banner" class="bg-image">
    <div class="overlay-content">
        <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">Products</h1>
        <div class="d-inline-flex mb-lg-5">
            <p class="m-0 text-white"><a class="text-white" href="Index">Home</a></p>
            <p class="m-0 text-white px-2">/</p>
            <p class="m-0 text-white">Products</p>
        </div>
    </div>
</div>

<!-- Product Cards Section -->
<div class="container product-container">
    <h2 class="text-center fw-bold mb-4">You Can Shop New ..</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var product in (IEnumerable<GP.Data.Entities.Product>)ViewBag.Model)
        {
            <div class="col">
                <div class="card h-100 custom-card shadow-lg">
                    <div class="image-container">
                        @if (product.Image != null)
                        {
                            var img = Convert.ToBase64String(product.Image);
                            var path = $"data:image/png;base64,{img}";
                            <img src="@path" alt="@product.Name" class="card-img-top">
                        }
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title">@product.Name.ToString()</h5>
                        <p class="product-price">@product.Price.ToString()$</p>
                        <p class="card-text">Short product description goes here.</p>
                        <div class="button-group">
                            <a asp-action="Details" asp-route-id="@product.ProductID" class="btn custom-blue-btn">Show Details</a>
                            <a href="#" class="btn custom-yellow-btn">Add to Cart</a>
                            @* <a asp-controller="Review" asp-action="AddReview" class="btn custom-blue-btn">Add Review</a> *@
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

Ecommerce_GP/Views/Product/SmartwatchIndex.cshtml
@* @model List<E_commerce_platform.Models.Product> *@


<!-- Background Image Section -->
<div class="bg-container">
    <img src="/img/Product.jpg" alt="Review Banner" class="bg-image">
    <div class="overlay-content">
        <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">Products</h1>
        <div class="d-inline-flex mb-lg-5">
            <p class="m-0 text-white"><a class="text-white" href="Index">Home</a></p>
            <p class="m-0 text-white px-2">/</p>
            <p class="m-0 text-white">Products</p>
        </div>
    </div>
</div>

<!-- Product Cards Section -->
<div class="container product-container">
    <h2 class="text-center fw-bold mb-4">You Can Shop New ..</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var product in (IEnumerable<GP.Data.Entities.Product>)ViewBag.Model)
        {
            <div class="col">
                <div class="card h-100 custom-card shadow-lg">
                    <div class="image-container">
                        @if (product.Image != null)
                        {
                            var img = Convert.ToBase64String(product.Image);
                            var path = $"data:image/png;base64,{img}";
                            <img src="@path" alt="@product.Name" class="card-img-top">
                        }
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title">@product.Name.ToString()</h5>
                        <p class="product-price">@product.Price.ToString()$</p>
                        <p class="card-text">Short product description goes here.</p>
                        <div class="button-group">
                            <a asp-action="Details" asp-route-id="@product.ProductID" class="btn custom-blue-btn">Show Details</a>
                            <a href="#" class="btn custom-yellow-btn">Add to Cart</a>
                            @* <a asp-controller="Review" asp-action="AddReview" class="btn custom-blue-btn">Add Review</a> *@
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

Ecommerce_GP/Views/Product/TabletProIndex.cshtml
@* @model List<E_commerce_platform.Models.Product> *@


<!-- Background Image Section -->
<div class="bg-container">
    <img src="/img/Product.jpg" alt="Review Banner" class="bg-image">
    <div class="overlay-content">
        <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">Products</h1>
        <div class="d-inline-flex mb-lg-5">
            <p class="m-0 text-white"><a class="text-white" href="Index">Home</a></p>
            <p class="m-0 text-white px-2">/</p>
            <p class="m-0 text-white">Products</p>
        </div>
    </div>
</div>

<!-- Product Cards Section -->
<div class="container product-container">
    <h2 class="text-center fw-bold mb-4">You Can Shop New ..</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var product in (IEnumerable<GP.Data.Entities.Product>)ViewBag.Model)
        {
            <div class="col">
                <div class="card h-100 custom-card shadow-lg">
                    <div class="image-container">
                        @if (product.Image != null)
                        {
                            var img = Convert.ToBase64String(product.Image);
                            var path = $"data:image/png;base64,{img}";
                            <img src="@path" alt="@product.Name" class="card-img-top">
                        }
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title">@product.Name.ToString()</h5>
                        <p class="product-price">@product.Price.ToString()$</p>
                        <p class="card-text">Short product description goes here.</p>
                        <div class="button-group">
                            <a asp-action="Details" asp-route-id="@product.ProductID" class="btn custom-blue-btn">Show Details</a>
                            <a href="#" class="btn custom-yellow-btn">Add to Cart</a>
                            @* <a asp-controller="Review" asp-action="AddReview" class="btn custom-blue-btn">Add Review</a> *@
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

Ecommerce_GP/Views/Product/WirelessHeadphonesIndex.cshtml
@* @model List<E_commerce_platform.Models.Product> *@


<!-- Background Image Section -->
<div class="bg-container">
    <img src="/img/Product.jpg" alt="Review Banner" class="bg-image">
    <div class="overlay-content">
        <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">Products</h1>
        <div class="d-inline-flex mb-lg-5">
            <p class="m-0 text-white"><a class="text-white" href="Index">Home</a></p>
            <p class="m-0 text-white px-2">/</p>
            <p class="m-0 text-white">Products</p>
        </div>
    </div>
</div>

<!-- Product Cards Section -->
<div class="container product-container">
    <h2 class="text-center fw-bold mb-4">You Can Shop New ..</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var product in (IEnumerable<GP.Data.Entities.Product>)ViewBag.Model)
        {
            <div class="col">
                <div class="card h-100 custom-card shadow-lg">
                    <div class="image-container">
                        @if (product.Image != null)
                        {
                            var img = Convert.ToBase64String(product.Image);
                            var path = $"data:image/png;base64,{img}";
                            <img src="@path" alt="@product.Name" class="card-img-top">
                        }
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title">@product.Name.ToString()</h5>
                        <p class="product-price">@product.Price.ToString()$</p>
                        <p class="card-text">Short product description goes here.</p>
                        <div class="button-group">
                            <a asp-action="Details" asp-route-id="@product.ProductID" class="btn custom-blue-btn">Show Details</a>
                            <a href="#" class="btn custom-yellow-btn">Add to Cart</a>
                            @* <a asp-controller="Review" asp-action="AddReview" class="btn custom-blue-btn">Add Review</a> *@
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>